fix: drop double "unable" in `README.md`

diff --git a/deploy/linux/xmrf-via-github-source b/deploy/linux/xmrf-via-github-source
--- a/deploy/linux/xmrf-via-github-source
+++ b/deploy/linux/xmrf-via-github-source
@@ -19,7 +19,7 @@ if [ -n "$XMRF_LGG" ]; then
 fi
 
 if [ -n "$(which git)" ]; then
-  echo "ERROR: Unable to find 'git', unable to proceed." >&2
+  echo "ERROR: Unable to find 'git', cannot proceed." >&2
 
   exit 1
 fi
